export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const REMOVE_WATCHLIST = "REMOVE_WATCHLIST";
export const ADD_WATCHED = "ADD_WATCHED";
export const REMOVE_WATCHED = "REMOVE_WATCHED";
export const MOVE_WATCHLIST = "MOVE_WATCHLIST";
